name: e2e tests

on:
  workflow_dispatch:

env:
  NODE_VERSION: 18.16.1
  PNPM_VERSION: 8.7.1
  NEXT_REPO: netlify/next.js
  NEXT_VERSION: netlify-testing
  NEXT_TEST_MODE: deploy
  TEST_CONCURRENCY: 8
  NEXT_TELEMETRY_DISABLED: 1
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BOT_AUTH_TOKEN }}
  NETLIFY_SITE_ID: 1d5a5c76-d445-4ae5-b694-b0d3f2e2c395

jobs:
  build-runtime:
    name: build runtime
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-${{ env.NODE_VERSION }}-

      - name: install runtime
        run: npm install
      
      - name: build runtime
        run: npm run build

      - name: upload runtime
        uses: actions/upload-artifact@v3
        with:
          path: '**'
    
  test-e2e:
    name: test e2e
    needs: [build-runtime]
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5]
    env:
      NODE_ENV: production
    steps:
      - name: get github token
        uses: navikt/github-app-token-generator@v1
        id: token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}
          repo: ${{ env.NEXT_REPO }}

      - name: checkout next repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.NEXT_REPO }}
          token: ${{ steps.token.outputs.token }}
          ref: ${{ env.NEXT_VERSION }}

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: install next
        run: pnpm install
        
      - name: build next
        run: pnpm build

      - name: download next runtime
        uses: actions/download-artifact@v3
        with:
          path: packages/next-runtime

      - name: add netlify cli
        run: pnpm add -g netlify-cli

      - name: run tests
        run: node run-tests.js -g ${{ matrix.group }}/5 -c ${TEST_CONCURRENCY} --type e2e

  validate-tests:
    name: validate tests
    needs: [test-e2e]
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
