name: run e2e tests

on:
  workflow_dispatch:

env:
  NODE_VERSION: '18.16.1'
  NEXT_VERSION: 'v13.5.0-netlify'
  TEST_CONCURRENCY: 8
  NEXT_TELEMETRY_DISABLED: 1
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BOT_AUTH_TOKEN }}
  NETLIFY_SITE_ID: 1d5a5c76-d445-4ae5-b694-b0d3f2e2c395

jobs:
  test-e2e:
    name: test e2e
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5]
    env:
      runtime-path: packages/runtime
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: enable pnpm/yarn support
        run: corepack enable

      - name: checkout next repo
        uses: actions/checkout@v3
        with:
          repository: 'netlify/next'
          ref: ${{ env.NEXT_VERSION }}

      - name: install and build next
        run: pnpm install && pnpm build

      - name: install playwright
        run: pnpm playwright install-deps && pnpm playwright install chromium

      - name: checkout runtime repo
        uses: actions/checkout@v3
        with:
          repository: 'netlify/next-runtime'
          path: ${{ runtime-path }}

      - name: install and build runtime
        run: npm install && npm build
        working-directory: ${{ runtime-path }}

      - name: install netlify cli
        run: npm -g netlify-cli

      - name: run tests
        run: NEXT_TEST_MODE=deploy node run-tests.js -g ${{ matrix.group }}/5 -c ${TEST_CONCURRENCY} --type e2e

  validate-tests:
    name: validate tests
    needs: ['test-e2e']
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
