name: run e2e tests

on:
  workflow_dispatch:

env:
  NODE_VERSION: 18.16.1
  NEXT_VERSION: v13.5.0-netlify
  NEXT_REPO: netlify/next.js
  NEXT_TEST_MODE: deploy
  TEST_CONCURRENCY: 8
  NEXT_TELEMETRY_DISABLED: 1
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BOT_AUTH_TOKEN }}
  NETLIFY_SITE_ID: 1d5a5c76-d445-4ae5-b694-b0d3f2e2c395

jobs:
  test-e2e:
    name: test e2e
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5]
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}
          repo: ${{ env.NEXT_REPO }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: |
            **/package-lock.json
            **/pnpm-lock.yaml

      - name: enable pnpm/yarn support
        run: corepack enable

      - name: checkout next repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.NEXT_REPO }}
          token: ${{ steps.get-token.outputs.token }}
          ref: ${{ env.NEXT_VERSION }}

      - name: checkout runtime repo
        uses: actions/checkout@v3
        with:
          path: packages/next-runtime

      - name: install
        run: pnpm install
        
      - name: build
        run: pnpm build

      # - name: install playwright deps
      #   run: pnpm playwright install-deps
        
      # - name: install chromium
      #   run: pnpm playwright install chromium

      - name: install netlify cli
        run: pnpm add -g netlify-cli

      - name: run tests
        run: node run-tests.js -g ${{ matrix.group }}/5 -c ${TEST_CONCURRENCY} --type e2e

  validate-tests:
    name: validate tests
    needs: [test-e2e]
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
